# Generated by Django 5.0.1 on 2024-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('grade', models.CharField(max_length=2)),
                ('address', models.TextField()),
                ('contactNumber', models.TextField(max_length=15)),
            ],
        ),
    ]
